### ISSUE TITLE
SpringViewProvider : specify errorView

### ISSUE THREAD

**Issue by lrozenblyum** [vaadin/spring#22]
Now there is no way to specify errorView in the same way like we can specify accessDeniedView
(errorView should be invoked when there is no corresponding view by name)

**Comment by hesara** [comment]
Now that a SpringNavigator can be injected, it can be used to set an error view. However, supporting error and access denied views together might require further changes in SpringViewProvider.getViewFromApplicationContext().

**Comment by hesara** [comment]
To implement this, the old fix for #50 needs to be redesigned from scratch.

The proposed behavior in order of checks would be:
* suitable view permitting access is found -> show it
* access is denied for a matching view -> if access denied view is defined, show it
* if error view is defined for the Navigator, show it
* if access denied view is defined, show it

This also needs to be documented and tested in more detail.

The order or the first two steps requires some rework, and the order of the last two steps requires checking for the existence of an error view (probably with customizations in SpringNavigator).

**Comment by hesara** [comment]
Implementation in #131 changes the current behavior so that the access denied view is not shown if there is no matching view, not even one with access denied. To match the previous behavior, an application can set the error view to be the same as the access denied view.

Thus, the final logic is
* suitable view permitting access is found -> show it
* access is denied for a matching view -> if access denied view is defined, show it
* if error view is defined for the Navigator, show it
