### ISSUE TITLE
Exception with Spring Boot 2.0.4.RELEASE and 2.1.0.M1

### ISSUE THREAD

**Issue by heruan** [vaadin/spring#331]
Vaadin Spring 10.0.0 brings in Spring Boot 2.0.2 and it works also in projects requiring 2.0.3, but breaks with 2.0.4 (and 2.1.0.M1).

The exception may vary, but it is probably related to this bugfix in Spring Boot [2.0.4.RELEASE](https://github.com/spring-projects/spring-boot/releases/tag/v2.0.4.RELEASE):

> Include DispatcherServlets only exposed as a ServletRegistrationBean in the mappings endpoint https://github.com/spring-projects/spring-boot/issues/13186

**Comment by snicoll** [comment]
What is the exception?

**Comment by heruan** [comment]
With 2.0.4.RELEASE:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type
'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPath' available:
expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

With 2.1.0.M1:

```
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean
definition with name 'dispatcherServletRegistration' defined in class path resource
[com/vaadin/flow/spring/SpringBootAutoConfiguration.class]: Cannot register bean definition
[Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3;
dependencyCheck=0; autowireCandidate=true; primary=false;
factoryBeanName=com.vaadin.flow.spring.SpringBootAutoConfiguration;
factoryMethodName=dispatcherServletRegistration; initMethodName=null;
destroyMethodName=(inferred); defined in class path resource
[com/vaadin/flow/spring/SpringBootAutoConfiguration.class]] for bean
'dispatcherServletRegistration': There is already [Root bean: class [null]; scope=;
abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true;
primary=false;
factoryBeanName=org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration$DispatcherServletRegistrationConfiguration;
factoryMethodName=dispatcherServletRegistration; initMethodName=null;
destroyMethodName=(inferred); defined in class path resource
[org/springframework/boot/autoconfigure/web/servlet/DispatcherServletAutoConfiguration$DispatcherServletRegistrationConfiguration.class]]
bound.
```

**Comment by snicoll** [comment]
That error is weird. It looks like you are creating your own `DispatcherServlet` when the vaadin support kicks in and you therefore replace the auto-configured mvc setup. When you do this, we can't create a `DispatcherServletPath` that is required down the road. 

Team, can you point me to the code that does this `DispatcherServlet` setup?

**Comment by heruan** [comment]
Thank you @snicoll for the interest!

Let's wait an answer from the team, but I guess it's around [SpringBootAutoConfiguration.java#L106](https://github.com/vaadin/spring/blob/315249bf1abbb362379d3063a90cb8714b94d3f6/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java#L106) where the JavaDoc states:

>  Creates a [ServletRegistrationBean](https://github.com/spring-projects/spring-boot/blob/71d26f9cebd9d342e5b24ca36d5122bef350e19b/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/ServletRegistrationBean.java) instance for a dispatcher servlet in case Vaadin servlet is mapped to the root.
> 
> This is needed for correct servlet path (and path info) values available in Vaadin servlet because it works via forwarding controller which is not properly mapped without this registration.

Maybe that premise changed in 2.0.4 and 2.1.0.

**Comment by snicoll** [comment]
@heruan thanks for trying to help but I know where the regression is coming from already. I'd like to understand why a `ServletRegistrationBean` is created manually in Vaadin's auto-configuration. That doesn't sound right to me.

**Comment by denis-anisimov** [comment]
Yes, `ServletRegistrationBean` is created in auto-configuration.
I don't see a reason why it's not right.

I think if something is not right then there should not be API which allows to do this.

**Comment by snicoll** [comment]
> I don't see a reason why it's not right.

Spring Boot's core auto-configuration manages the `DispatcherServlet` and offer various ways of customizing it. While it's perfectly ok in an advanced scenario to override this process with custom code, this is certainly less relevant in an auto-configuration. When adding the vaadin starter in an app, users expects the auto-configuration to "augment" the available features and integrate with existing ones. 

> I think if something is not right then there should not be API which allows to do this.

I think you are vastly oversimplifying the problem with that kind of statement. Having such an opinion has a consequence: you're more likely to break things: if you override stuff that way, you're also responsible to make sure they still work in the long run. 

Can we take a step back? I'd like you understand why you're doing this.

**Comment by denis-anisimov** [comment]
> Can we take a step back? I'd like you understand why you're doing this.

Just because it's possible (and I don't know another way).
This is a consequence of my sentence: I think if something is not right then there should not be API which allows to do this.

I'm absolutely serious: I have no any intention to break things specifically. So there is no evil intent.
I don't know all the agreement which are somehow hidden in Spring.
So I made it somehow so that it worked.
Nothing prevented me from doing this. So why not?

I'm pretty sure that good API has to be designed in the way which allows things that should be allowed and doesn't allow things which should not be done.
I was always able to do it so this is not oversimplification at all.
Spring is a kind of magic and I don't see what I can do and what I can't do.

So please just let me know what else should I do to be able to register custom servlet in the auto-configuration ?

**Comment by snicoll** [comment]
> Just because it's possible (and I don't know another way).

That doesn't answer my question at all. IMO, your sentence does not make much sense in the context of what Vaadin Spring should do: this is a library, not a custom project. So you have to know and I am happy to help if you don't.

I've already answered what the use of the API is for: advanced scenario and yours is not.

> So please just let me know what else should I do to be able to register custom servlet in the auto-configuration ?

That's not what [that code does](https://github.com/vaadin/spring/blob/master/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java#L106). It overrides a core piece for Spring Boot for a reason that I don't understand. 

As I've asked already, can you please explain why you're doing this?

**Comment by heruan** [comment]
End-user intromission, since I'd like to understand better how this works from both perspectives 🙂 

I see Vaadin's providing `ServletRegistrationBean`s at [L75](https://github.com/vaadin/spring/blob/315249bf1abbb362379d3063a90cb8714b94d3f6/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java#L75) and [L106](https://github.com/vaadin/spring/blob/315249bf1abbb362379d3063a90cb8714b94d3f6/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java#L106): I understand the latter is just a "fix" for mapping the root context, while the former actually register the servlet with a special mapping for push requests; maybe this is the cause of needing this?

**Comment by denis-anisimov** [comment]
I've been trying to answer to the original concern:

> I'd like to understand why a ServletRegistrationBean is created manually in Vaadin's auto-configuration. 

There are two methods which register `ServletRegistrationBean`. 
Both of them register the custom servlet. And I considered this question as why do I use `ServletRegistrationBean` to register a custom servlet.

So your concern is actually is the `DispatcherServlet` registration.
Now at least I understand what we are talking about.

The answer is:
- It's not clear for me what's the `DispatcherServlet` is. And sorry, this is not my problem. This is problem of bad documentation and weak API.
- Why should I have two servlets at all: one which I register as Vaadin servlet and another is `DispatcherServlet`.
- It became more clear after we had got a bug about inability to use Spring endpoints with Vaadin application because Vaadin servlet handles all the URLs and don't give a chance to any other endpoint to handle their requests .
- Now when the servlet is mapped to the root then we do a trick which register the Vaadin servlet to another URL and forwards requests to the root URL to the servlet. And it should work out of the box. But it doesn't. This comment explains the reason why it's needed : `This is needed for correct servlet path (and path info) values available in Vaadin servlet because it works via forwarding controller which is not properly mapped without this registration.`

**Comment by denis-anisimov** [comment]
In reality once I understood that we are talking about `DispatcherServlet` the answer is pretty simple:
because it doesn't work without this.
I'm not sure about PUSH requests. I don't remember exact problems but it's something about wrong servlet path and path info with forwarding applied (which we use in case of root mapping).
And I would also like to get an answer to the question: why it doesn't work out of the box and this trick was required to get proper servlet path and path info?

**Comment by heruan** [comment]
https://github.com/vaadin/flow/issues/4356 might be a use case when the user wants a different mapping for the servlet (not root) but setting the custom mapping the application breaks since it's not able to find `/frontend` resources.

**Comment by carddamom** [comment]
I'm also having this problem, and for me placing:

> vaadin.urlMapping=/app/*

Inside application.properties, solves my problem, it changes the root of the vaadin app, but since I also wanted to provide a RestApi for other clients (read mobile clients), I was gonna do it anyway, so cool...

**Comment by denis-anisimov** [comment]
OK, now I have time to look at this finally.

The reason why dispatcher servlet is explicitly configured via `ServletRegistrationBean` is the code in our `WebJarServer` class which handles WebJar URIs.
The method `tryServeWebJarResource` tries to handle web jar URIs and inside Spring boot with default `DispatcherServlet`  logic fails.

Here is the example how it fails:
- the incoming request URI is `/frontend/bower_components/webcomponentsjs/webcomponents-loader.js/`.
- `request.getServletPath()` returns `/frontend/bower_components/webcomponentsjs/webcomponents-loader.js/` 
- `request.getPathInfo()` returns `null`.
- the resulting webJarPath is `/webjars/webcomponentsjs/webcomponents-loader.js/null`.

So several things to note:
- No any `PUSH`. Just easiest Vaadin application doesn't work without a custom `DispatcherServlet` (even though this is not a proper fix). In general : Vaadin doesn't work at all in its current state with default `DispatcherServlet` if it's mapped to the root context.
- Why there is `/webjars/webcomponentsjs/webcomponents-loader.js/`  URI at all? The original URI was ``/webjars/webcomponentsjs/webcomponents-loader.js` but it has been redirected via 302 response to the `/webjars/webcomponentsjs/webcomponents-loader.js/` (as I see in the browser network inspector).
- Everything works fine in case of overriden `DispatcherServlet`: the original URL is not redirected to the incorrect one. 

There are very good questions:
- why it's redirected at all
- why it's not redirected with overridden `DispatcherServlet`.

It might be that instead of overriding a `DispatcherServlet` it needs to be just configured additionally.

That's the analysis which I see and can say right now.
Will see what we can do to fix the wrong redirection and get rid of custom `DispatcherServlet`.

**Comment by snicoll** [comment]
@Legioth no, that's really a workaround for the underlying problem. We need to figure out why it is necessary that Vaadin's auto-config exposes a `DispatcherServlet`. Looking at the code, it looks quite similar to what we do (if we merge #335, it is almost identical) so it looks like the good fix would be to remove that altogether. 

It looks like it is not possible at the moment (based on the analysis above).

**Comment by denis-anisimov** [comment]
There are two PRs to fix the exception 
- https://github.com/vaadin/spring/pull/335
- https://github.com/vaadin/spring/pull/336

So the workaround is provided.
But we should find a proper way to fix the behavior with redirection.

**Comment by snicoll** [comment]
This is an entirely different issue. Bean overriding has been forbidden by default in 2.1 (one more reason for not doing what this does at the moment).

Reading the release notes [should help](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1.0-M1-Release-Notes#bean-overriding).

**Comment by heruan** [comment]
Thank you @snicoll for the quick feedback. I'll try enabling bean overriding as a workaround for now, hoping for a better solution from the module.

Do you have any suggestion on how to achieve Vaadin's servlet needs?

**Comment by denis-anisimov** [comment]
One more aspect of this issue is : 
https://github.com/vaadin/vaadin-upload-flow/issues/84.

The issue is a consequence of hack with dispatcher servlet.
If the application is not mapped to the root then there is no the issue.

**Comment by heruan** [comment]
Worth noting also that as @snicoll said bean overriding has been forbidden in Spring 2.1.0, which will released October 29th. Since it will bring major updates to the dependency hierarchy (e.g. Hibernate 5.3) I expect many users will upgrade and face these issues.

It would be great to have this solved properly before the release (2.1.0.M4 ATOW).

**Comment by knoobie** [comment]
Spring Boot 2.1 is now released. (https://github.com/spring-projects/spring-boot/releases/tag/v2.1.0.RELEASE) 

Do we have any progress here?

**Comment by pleku** [comment]
Unfortunately we have not had time yet to take another stab at this, but will do so soon, this or next week.

**Comment by pleku** [comment]
We have another working workaround and are also close to finding the proper fix without the need for the workaround. Regardless which approach we use first, next week we should have platform releases that work with Spring Boot 2.1. (v10, v11 and v12)

Sorry for keeping you on hold before being able updating to Spring Boot 2.1, we should have looked at this earlier - my bad.

**Comment by knoobie** [comment]
Do you plan to support Spring Boot 2.1 with V8 as well?

**Comment by heruan** [comment]
Thank you @pleku for the update! I peeked at the workaround and it's ingenious, but I admit I'm very curious to see what a proper fix might be; I don't deny I spent much time trying to find one, but I wasn't able to get to it yet.

**Comment by mstahv** [comment]
@knoobie Do you have some issue? V8 should work just fine, just updating Spring Boot version should be enough. Haven't updated all my examples, but verified with [spring-data-vaadin-crud](https://github.com/mstahv/spring-data-vaadin-crud) that at least simple apps work without issues. If you have some issue with Vaadin 8, file a separate ticket for that.

**Comment by knoobie** [comment]
@mstahv thanks Matti! Did not update our "old" app, just wanted to ask before I work on it - to save some time.
