### ISSUE TITLE
vaadin-spring 3.1.1 still uses Spring 4.3.9 instead of 5

### ISSUE THREAD

**Issue by gbvcbjgkfvkgcbkj** [vaadin/spring#352]
Hi,

we are still on Vaadin 8 in our project. Therefore we are using vaadin-spring 3.1.1, which is dependent on Spring 4.3.9. When we are switching the project to Spring 5 we are getting ClassNotFoundExceptions due to changes in Spring that are not reflected in vaadin-spring.

What is the timeline to switch vaadin-spring to Spring 5?

Regards,
Chris

**Comment by SomeoneToIgnore** [comment]
Hello.

Newer versions of vaadin-spring (https://github.com/vaadin/spring/releases/tag/10.0.4) use `spring-boot-dependencies:2.0.4.RELEASE` which uses Spring 5 under the hood.
The only drawback would be the fact that the those plugin versions are compatible with Vaadin 10, not Vaadin 8.

I am not aware of any plans related to Spring 5 and Vaadin 8 interop.

**Comment by gbvcbjgkfvkgcbkj** [comment]
That means Vaadin 8 will get no further support for vaadin-spring?

**Comment by Legioth** [comment]
If there's anything we can reasonably do to ensure previous versions of the Spring add-on can still be used with Spring 5.x, then we should do that. This helps hugely with migration since you can first update your application to use Spring 5 and only then update the Vaadin version or introduce MPR into the project, instead of having to do both at once.

We did test compatibility a while ago when Spring Boot 2.0.0 (which uses Spring 5.x) was released: https://github.com/vaadin/spring/issues/190. You are either using some functionality that we didn't test, or then there have been other changes since then.

Could you provide more details on exactly what goes wrong when you try using Spring 5.x, or alternatively provide a simple test application?

**Comment by gbvcbjgkfvkgcbkj** [comment]
I think my problem would be solved by simply replacing the Spring 4 dependency with Spring 5. Then my whole environment would be at version 5.

**Comment by snicoll** [comment]
You should have dependency management in your build rather than relying what independent libraries build against to. 

If you’re using spring Framework there is a bom you must use regardless to get consistent versions. If you’re using spring boot, there is a larger ecosystem available and both a starter parent or a bom.

**Comment by snicoll** [comment]
That said you reported CNFE in your report. Can you please share more details about those? (Stacktrace or a sample)

**Comment by jlangch** [comment]
Maybe it helps to clarify. 

I successfully migrated my large Vaadin 8.5.2 appliaction to vaadin-spring 3.3.1 and springframework 5.1.0 (previously 4.3.18) and it works fine.

So this setup basically should work.

**Comment by gbvcbjgkfvkgcbkj** [comment]
If vaadin-spring works with Spring 5 (which it didn't for me, because I get these exceptions during the startup from a Kafka component), then the Spring dependency of vaadin-spring can be updated to a 5.x.x verision, right?

**Comment by Legioth** [comment]
@gbvcbjgkfvkgcbkj It goes both ways. Updating the Spring version dependency to 5.x would instead have a significant risk of causing problems for those who still use Spring 4.x, which is still the most common case for the Vaadin 8 version of the plugin.

**Comment by snicoll** [comment]
> So I should be doing this for every vaadin-spring reference:

I have no idea how you came to that conclusion. Why would you want to exclude `spring-web` exactly? Perhaps you could search/ask on StackOverflow how to setup your project so that dependencies are managed properly. This [article should help you get started](https://www.baeldung.com/spring-maven-bom)

**Comment by gbvcbjgkfvkgcbkj** [comment]
Sorry, I think you are right. My problem was a version conflict. I guess I can solve like described in this article: https://dzone.com/articles/solving-dependency-conflicts-in-maven

**Comment by Legioth** [comment]
I'm going to assume that there isn't anything to fix here. Please add a message here or file a new more specific issue if there's still some compatibility issues after ensuring that there are no conflicts between different Spring modules.
