### ISSUE TITLE
@PreserveOnRefresh doesn't preserve UI bean store and UI scoped beans

### ISSUE THREAD

**Issue by edler-san** [vaadin/spring#473]
@PreserveOnRefresh in Vaadin 8 preserved the actual UI instance, which included the UI bean store and thus all UI scoped beans. This differs from the behaviour of @PreserveOnRefresh within Vaadin 14 where UIScope'd beans can differ after a refresh.

**Comment by pleku** [comment]
I would expect the same oversight has happened for cdi add-on too.

**Comment by simasch** [comment]
This is a very important issue. 
If the UIScoped beans are not preserved the Spring integration is completely useless.

**Comment by TatuLund** [comment]
Check this one: https://vaadin.com/forum/thread/17810577/ui-being-instantiated-over-and-over-again-in-default-vaadin-14-0-1-app

**Comment by denis-anisimov** [comment]
There will be two comments for different target auditory:
- the first comment is for the ticket reporter (user world)
- the second comment is about fixing the ticket (implementation world)

I will make them separately. See below.

**Comment by denis-anisimov** [comment]
The user level comment:

it's not logical to expect that UI scoped beans are preserved when `@PreserveOnRefresh` is used.
Please note that `@PreserveOnRefresh` can be attached to any view component.

So you may have two component: one has `@PreserveOnRefresh` and another doesn't.
They both are attached to the same `UI` instance. It means that if we preserve ui scoped beans then they will be reused for both components. But they should be reused only for the `@PreserveOnRefresh` and can't be reused for another component which doesn't have this annotation.

So making the functionality as requested we will introduce a bug.
It means that we may not do this in the proposed way.

On the other hand the feature-wise request makes sense.
So we have two suggestion for this:
- use some way (non-existent at the moment) to make `UI` instance "preserved on refresh" as a whole instead of making an individual view. It may not be done currently with `@PreserveOnRefresh` . We need a new API/config parameter for this. There is a ticket about that: https://github.com/vaadin/flow/issues/6395.
- use proper scopes for that situation. E.g. you attach `@PreserveOnRefresh` to a view or layout and it should be a way to use a scope for this layout/view. This is not implemented yet also. Here is already a ticket for this: https://github.com/vaadin/spring/issues/263.

I will close this ticket : the ticket https://github.com/vaadin/spring/issues/263 should be considered as a fix for this once it's implemented.
You should use `RouteScope` to preserve beans between refresh with the target component where 
`@PreserveOnRefresh` is used.
It's also possible to implement a workaround for UI preserved on refresh in this case: just use one main layout with `@PreserveOnRefresh` and scope for every your view. This main layout will play a role of `UI`.

**Comment by denis-anisimov** [comment]
The second comment about the implementation will be written in the https://github.com/vaadin/spring/issues/263.
