### ISSUE TITLE
Component's JsModule not discovered if used in UIInitListener in a VaadinServiceInitListener Spring Bean

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/spring#475]
Originally reported in https://github.com/vaadin/flow/issues/5792

In bakery the offline banner is added during UI Init
```
@SpringComponent
public class ConfigureUIServiceInitListener implements VaadinServiceInitListener {

@Override
public void serviceInit(ServiceInitEvent event) {
    event.getSource().addUIInitListener(uiEvent -> {
        final UI ui = uiEvent.getUI();
        ui.add(new OfflineBanner());
        ui.addBeforeEnterListener(this::beforeEnter);
    });
}
...
```

Actual result is
>Frontend dependencies have not been analyzed for com.vaadin.starter.bakery.ui.components.OfflineBanner

Adding a dummy reference in a route workarounds the issue

**Comment by denis-anisimov** [comment]
The fix which has been done in Flow doesn't work in Spring.
The reason is : we are using `DevModeServletContextListener` in Spring add-on which uses `findBySuperType` method based on Spring `ClassPathScanningCandidateComponentProvider` and `AssignableTypeFilter`.
This functionality doesn't return a lambda which is the `UIInitListener` implementation in the described case.

I think I may add `VaadinServiceInitListener` implementations in addition (on fact even instead of) `UIInitListener` impls.
We need only an entry points which contains a code which should be analyzed for `JsModule` annotations. So using a `VaadinServiceInitListener` in this case will work and this is a proper replacement of `UIInitListener`  since there is no other logical way to add a `UIInitListener` : in any other way it's just too late to add it since it won't be executed (UI will be initialized already).
Also it won't significantly affect the performance .
