### ISSUE TITLE
IllegalStateException when running a Vaadin Spring project on WebLogic server

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/spring#502]
When trying to run [skeleton-starter-flow-spring](https://github.com/vaadin/skeleton-starter-flow-spring) on WebLogic server the following exception is thrown.
```
java.lang.IllegalStateException: strict servlet API: cannot call getOutputStream() after getWriter() 
	at weblogic.servlet.internal.ServletResponseImpl.getOutputStream(ServletResponseImpl.java:314) ~[com.oracle.weblogic.servlet.jar:12.2.1.4]
```
### Steps to reproduce
- Clone [skeleton-starter-flow-spring](https://github.com/vaadin/skeleton-starter-flow-spring)
- Change the packaging to war in pom.xml
- Exclude `spring-boot-starter-tomcat` from `vaadin-spring-boot-starter` dependency in pom.xml
```
<exclusion>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-tomcat</artifactId>
</exclusion>
```
- Add `javax.servlet-api` dependency to pom.xml
```
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>javax.servlet-api</artifactId>
</dependency>
```
- Create a Run/Debug configuration in IntelliJ IDEA Ultimate and add war artifact to it
- Run the project and navigate to http://localhost:7001/spring-skeleton-2.0-SNAPSHOT/
- In the log, you can see the exception

Note that doing the instructions provided in Spring Boot documentation on [how to deploy a War to WebLogic](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-weblogic) didn't make any change.
### Versions
- Java 8
- Vaadin 14.0.7 (The same behavior with 14.1-SNAPSHOT)
- IntelliJ IDEA Ultimate 2019.2
- WebLogic 12.2.1.4.0

[Full Log](https://github.com/vaadin/spring/files/3690544/weblogic-vaadin-spring.log)

Another issue that can be seen in the log is webpack error like the following. 
```
[webpack] ERROR dev-webpack - ERROR in ../target/frontend/generated-flow-imports.js
[webpack] ERROR dev-webpack - Module not found: Error: Can't resolve '@vaadin/flow-frontend/datepickerConnector.js' in '/Users/mehdi/Documents/GitHub/skeleton-starter-flow-spring-test/target/frontend'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 12:0-54
```

**Comment by mshabarov** [comment]
This exception is reproduced on `V14.0.7`, but not on `V14.1.18` and `V15.0.1`, however,  `Module not found` errors are presented permanently on all versions.
Root cause investigation is in progress.

**Comment by mshabarov** [comment]
UPDATE:

According to [ServletResponse specification,](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletResponse.html#getOutputStream--) `java.lang.IllegalStateException` is thrown if the `getWriter() `method has been called on this response instance prior to `getOutputStream() `method. 

`PwaHandler.handleRequest()` calls `getWriter() `method if some conditions are met. On the other hand, `DevModeHandler.serveDevModeRequest()` calls `getOutputStream()` if another conditions are met. 

In `V14.0.7` (as well as in elder version apparently) those conditions could intersect so as to provide sequential `getWriter()` and `getOutputStream() `calls, which is prohibited.

The crucial code modification brought up the different behaviour is in `DevModeHandler.isDevModeRequest`:

```
request.getPathInfo().matches(".+\\.js") <----- old

request.getPathInfo().startsWith("/" + VAADIN_MAPPING) <------ new
```

Thus, in most recent versions (e.g. 14.1.18, 15.0.1) `getWriter()` and `getOutputStream()` calls are completely separated from each other, and this is the reason why the issue is not reproduced on recent versions.

To conclude, this issue was eliminated by indirect code changes related to features/improvements. I don't see any action needed for this issue. However, the issue with `Module not found `should be solved since it does'n allow the UI to be rendered at all.  Working on that.

**Comment by mshabarov** [comment]
UPDATE: 

**Observations on `V15.0.1`:**

1. The following errors are presented in a log while application is started:

```
ERROR in ../node_modules/@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/mikhail/workspace/vaadin/skeleton-starter-flow-spring-4/skeleton-starter-flow-spring/node_modules/@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box.js'
 @ ../target/frontend/generated-flow-imports.js 39:0-65
 @ ./index.ts
```

2. `node_modules/@vaadin` folder does not contain vaadin UI components on client side, so the UI (text field and button) is not rendered.

**Webpack compilation error root cause:**

1. Webpack errors described above are the consequence of npm install failure.
2. Npm install failed due to incomplete `package.json` dependancies, there should be a list of `@vaadin/...` components.
3. `Package.json` isn't updated correctly with proper dependancies because there are no UI-annotated classes (`@JsModule`, `@NpmPackage` etc.) found in
classpath, and `TaskUpdatePackages` does not update the `package.json` file thus.
4. No classes found because `VaadinServletContextInitializer.findByAnnotationOrSuperType()` method receives empty base package list.
5. Base package list is empty because `vaadin.whitelisted-packages` property is absent.

**Workaround**:

Setting `vaadin.whitelisted-packages=com/vaadin/flow/component` solves the issue, however this is default package for components and it should has been added
automatically (see [documentation](https://vaadin.com/docs/v14/flow/spring/tutorial-spring-configuration.html)).

There are still some intermediate exceptions in the log file, but it doesn't affect affect the behaviour apparently, application is started and UI rendered fine:

```
<17-Mar-2020 15:47:30,020 o'clock EET> <Warning> <HTTP> <BEA-101162> <User defined listener com.vaadin.flow.spring.VaadinServletContextInitializer$AnnotationValidatorServletContextListener failed: java.lang.AbstractMethodError: Method com/vaadin/flow/spring/VaadinServletContextInitializer$AnnotationValidatorServletContextListener.contextDestroyed(Ljavax/servlet/ServletContextEvent;)V is abstract.
java.lang.AbstractMethodError: Method com/vaadin/flow/spring/VaadinServletContextInitializer$AnnotationValidatorServletContextListener.contextDestroyed(Ljavax/servlet/ServletContextEvent;)V is abstract
	at com.vaadin.flow.spring.VaadinServletContextInitializer$AnnotationValidatorServletContextListener.contextDestroyed(VaadinServletContextInitializer.java)
	at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:720)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	Truncated. see log file for complete stacktrace
> 
```

**Conclusion**: workaround is simply add the property `vaadin.whitelisted-packages=com/vaadin/flow/component `to `application.properties`. However, it should be added by
default on flow side according to documentation. This looks like a bug.

**Comment by denis-anisimov** [comment]
This requires further investigation.
`vaadin.whitelisted-packages` doesn't have to be set.

I don't know why but at the moment I don't see any code in the `VaadinServletContextInitializer` which reads this property at all.
But I see `CustomResourceLoader` class and it's method `shouldPathBeScanned`.
It contains a code : 
```
if (defaultWhiteList.stream().anyMatch(path::startsWith)) {
                return true;
            }
```

and `defaultWhiteList`  contains `component`  package .
Which means that `com/vaadin/flow/component`  should be used to scan for classes.

So it's not clear for me why classes are not found.

I suggest to debug the code and see what's going on there.
- Why classes are filtered out (is it done by the `CustomResourceLoader` ) ?
- how exactly the behavior is affected by the `vaadin.whitelisted-packages`  ?
- why the default whitelist doesn't contain the `com/vaadin/flow/component`  package.

It seems that the absence of `com/vaadin/flow/component`  as a default whitelisted package is the main cause of this bug.
So the only remaining thing is to make sure that default whitelist has the proper value and detect why it doesn't have it with WebLogic.

**Comment by mshabarov** [comment]
@denis-anisimov , yes, I agree this issue need more investigation efforts.

Here are my thoughts/observations on that:

1. Yes, I agree, `vaadin.whitelisted-packages` doesn't have to be set. This is stated in documentation and `spring-skeleton` app runs perfect without it, when running outside of WebLogic. Adding this property is just a workaround,but the root cause seems to be different because, again, spring-skeleton runs fine with no such a property explicitly added.

2. `vaadin.whitelisted-packages` property is being loaded in `VaadinServletContextInitializer` constructor:

```
  String whitelistProperty = appContext.getEnvironment()
                .getProperty("vaadin.whitelisted-packages");
```

3. When running inside WebLogic, there are actually two sequential "startup" phases (which probably is abnormal):
      1) WebLogic servlet container calls `DevModeInitializer.onStartup()`, package.json update, 
      npm install and webpack compilation are completed successfully then.
      
      2) Spring calls `VaadinServletContextInitializer.onStartup()`, this time webpack compilation fails.

In the case 2) the component classes are obtained this way:

```
Set<Class<?>> classes = findByAnnotationOrSuperType(basePackages,
        customLoader, annotations, superTypes)
                .collect(Collectors.toSet());
```

4. If `vaadin.whitelisted-packages` is set, then `customWhitelist` is not empty -> `basePackages` initialized properly:

`basePackages = new HashSet<>(getWhiteListPackages());`

We can even set something different than Component package, it should force the `basePackages` initialization anyway. 
Non-empty `basePackage` forces `findByAnnotationOrSuperType`() to scan for classes properly.

5. Default whitelist does contain the `com/vaadin/flow/component` package:

```
private static final List<String> DEFAULT_WHITE_LISTED = Stream
        .of(Component.class.getPackage().getName(),
                Theme.class.getPackage().getName(), "com.vaadin.shrinkwrap")
        .collect(Collectors.toList());
```

but it is ignored and not placed into `basePackage`.

I would pay a focus on how `findByAnnotationOrSuperType()` works under the hood. Key point here is `customLoader`. My suggestion is that the Weblogic and Spring boot contexts are overlapped in terms of classpath and classloaders and it does not allow `customLoader` to find the wanted classes.

**Comment by denis-anisimov** [comment]
OK, now I understand the issue.

The `vaadin.whitelisted-packages`  doesn't related anyhow to `CustomResourceLoader::defaultWhiteList` (it's quite confusing that we have to unrelated white lists).

The property value is used to set `customWhitelist`  .
The value of the latter field is used in `getWhiteListPackages` method.
But `getWhiteListPackages`  method is called _only_ if white list is explicitly set (i.e. the property is explicitly set).

```
if (isWhitelistSet()) {
                basePackages = new HashSet<>(getWhiteListPackages());
            } else {
                basePackages = Collections.singleton("");
            }
```

If white list is not explicitly set then base packages are set to a singleton list with an empty string as a root which is used to search .

Apparently Spring doesn't like using ""  as a package name .

So the questions are :
- is it true that this is very specific for WebLogic ? So in every other server `isWhitelistSet()` returns `false` if the property is not explicitly set and `basePackages` is set to `Collections.singleton("")`  and Spring is able to find the annotated classes using `""` as a package to search.
- based on previous: does it mean that this is a Spring behavior that it's able to find annotated classes inside `""` package for almost all cases and it's not able to find anything only in WebLogic case (quite weird).
- or it's only because in WebLogic `isWhitelistSet()` returns `false` and it returns `true`  ( for some reason) in other cases and in fact `basePackages` is never `""` (except WebLogic).
- if this is Spring who is working indeterministic (is able to find in one case and is not able to find with the same prerequisites) then we have to deal with this: find some workaround again.

I would try to use `basePackages = Collections.singleton("/");` (or `basePackages = Collections.singleton(".");`) and check whether it works.
Another way could be : try to search somehow ( don't know how exactly ) all top level packages and use the result list as  a value for `basePackages`.

Why do we need to do this instead of using `vaadin.whitelisted-packages` hardcoded value:
it's incorrect.
User may have a number of add-ons in his project within any packages. If we set explicitly `vaadin.whitelisted-packages` to some value then we may loose packages.

**Comment by mshabarov** [comment]
Reproduced on WildFly Full 18.0.1.Final for [bookstore-example](https://github.com/vaadin/bookstore-example)

**Comment by mshabarov** [comment]
As it turned out, the Spring context starts Dev Mode initialisation by invoking `DevModeInitializer.initDevModeHandler()` although it has already been started by Servlet Container. 
The solution is to check if Dev Mode already started, and skip it if necessary.
