### ISSUE TITLE
Spring Boot 2.2 and Vaadin 14 Session Timeout

### ISSUE THREAD

**Issue by tamademicheli** [vaadin/spring#513]
Tomcat Session get destroyed (Default tserver.servlet.session.timeout = 30m and vaadin max session 30m * 60 ) although the heartbeat (Default 300s) is set. 

This should not happen since the heartbeat should keep the session alive

**Comment by mshabarov** [comment]
Hello @tamademicheli , could you please provide the steps to reproduce this issue? Thanks

**Comment by grass83** [comment]
Hello, 
I am having a similar session closed behaviour, using Vaading 14 and Spring Boot 2.2.0. The problem is when I run two or more different apps, each one load in a browser tab and listen one port. When the first app is loaded in the browser (firefox or chrome), everything works fine but, if I access to other app in other tab of the same browser, the first app session seems to be closed and the UI restarted.
The steps to reproduce this behaviour are the following:

1 - Download and unpack two example applications from https://vaadin.com/start/v14. Technologies are Vaadin 14 and Spring Boot. Each application was named different, in my case VaadinSpringbootTest1 and VaadinSpringbootTest2.

2 - Modify application.properties file changing the server port in VaadinSpringbootTest2, forcing it to listen 9090 port:
	
	server.port=9090

So, we have an app listening on 8080 and other app listening on 9090.

3 - Launch the two apps, each one in a terminal, using maven:
	
 	mvn spring-boot:run

4 - Start firefox and open two tabs. On the first tab, access to localhost:8080. Everything is ok, app works. On the second tab, access to localhost:9090. The app is loaded and works fine but, if I come back to the first tab, and I try to click on the button, the app is restarted.

5 - After this, if I play with both tabs, apps are continuously restarted.

No error traces are showed, neither session configuration parameters added.

I have tested this behaviour using RedHat 8.2, OpenJDK 11.0.7 and Maven 3.6.3.

If you need any further informations, please ask.
Thank you very much for your help.

**Comment by denis-anisimov** [comment]
Thank you very much for the exact steps to reproduce.
I'm able to reproduce this exactly as described 👍

**Comment by denis-anisimov** [comment]
This happens because of cookies.
Every Java servlet application (Vaadin is a Servlet based framework) uses `JSESSIONID` cookie.
Cookies are set per domain and they are not based on port number: http://tools.ietf.org/html/rfc6265
You may also refer to the https://stackoverflow.com/questions/1612177/are-http-cookies-port-specific for a short answer.

So both of your application are running on localhost and the only difference is just a port.
The domain is the same and cookies are the same. Applications reuses the session from each other which leads to this effect.
The same will happen if you have two plain Java Servlets.

Technically we can't do anything with this.
You should not use two Java servlet based apps on the same domain.
It means that you should use a different domain for  different apps.
E.g. one app may be loaded via `localhost:8080` , the other one via `127.0.0.1:9090`.
Also you may use `/etc/hosts`  to assign additional domain addresses to your localhost IP.

**Comment by grass83** [comment]
Hello @denis-anisimov,
I am sorry I did not realised about that before. Your answer is a very valuable source of information.
Thank you very much for your response.
