### ISSUE TITLE
SPIKE: Investigate how we could support @ViewScope for migrating apps

### ISSUE THREAD

**Issue by pleku** [vaadin/spring#557]
Related to https://github.com/vaadin/spring/issues/508, we should investigate how we can make it so that V7/V8 apps that are migrating to V14 can keep on working when those use `@ViewScope` extensively. 

It might be that just implementing `@RouteScope` #263 for V14 would make sense, but that has some other factors https://github.com/vaadin/spring/issues/263#issuecomment-527863137
Being able to use `@RouteScope` would bring other benefits too and it has been requested.

Anyway, we should investigate what would be the best way to allow apps utilizing `ViewScope` to work in 14, and try to get an initial idea on how many things would be required to be done for this.

**Comment by mstahv** [comment]
We could probably get a rough idea fi RouteScope would help if we test similar setup with CDI (as it already has RouteScope). If the issue doesn't exist or is smaller, then it is a good proof point to take RouteScope to the top of the backlog soon (although currently scheduled in a larger Spring enhancements project later this year).

**Comment by pleku** [comment]
So the idea would be to use a CDI v8 application (https://github.com/vaadin/cdi-tutorial/pull/10) with `ViewScope` and then port that to v14 with MPR and determine what would be needed to be able to keep the code the same (?) or replace it with `@RouteScope` and its owner using the new CDI add-on features.

**Comment by denis-anisimov** [comment]
Flow has no `View` concept  and this is why it's hard to say how exactly `ViewScope`  should be used.

It has no sense to inject a `ViewScoped` component into a view : doesn't matter which scope is used for the component.
Since it's injected it's preserved during view lifecycle. 
Using injected `Instance` as in vaadin/cdi-tutorial#10 also doesn't show why it makes sense to use `ViewScoped`  : the instance is not injected directly but there is no clear reason to not inject `TitleLabel` field  directly instead of  `Instance`.

There are a couple scenarios when `@RouteScoped`  component may be used:
- for a component in the navigation hierarchy
- for a bean/component which don't participate in navigation directly

The first case doesn't require any injection point at all: everything works out of the box. But the `@RouteScoped` component should be in a navigation chain: e.g. navigation target route.

```
@UIScoped
public class MainLayout extends Div implements RouterLayout {

    public MainLayout() {
        add(new RouterLink("root", NavigationTarget.class));
        add(new RouterLink("another", AnotherTarget.class));
    }
}

@ParentLayout(MainLayout.class)
public class InterimLayout extends Div implements RouterLayout {

}

import com.vaadin.ui.Button;
import com.vaadin.ui.Label;

@Route(value = "another", layout = InterimLayout.class)
@RouteScopeOwner(MainLayout.class)
@RouteScoped
public class AnotherTarget extends Div implements HasLegacyComponents {

    public AnotherTarget() {
        Label label = new Label();
        add(label);
        Button button = new Button("set label text",
                event -> label.setValue("bar"));

        add(button);
    }

}
```

In this example `AnotherTarget` is still a Flow component which contains V8 components.
The component is `@RouteScoped` with `MainLayout.class`  as a owner but it has ` InterimLayout.class` in between.

There is no injection point : the `AnotherTarget`  instance will be created automatically and will be used as `"another"` navigation target . The instance won't be lost on navigation if `MainLayout`  is still in the navigation chain (button set value in the label on click and that allows to see that the component is preserved after navigation to `"root"`  and back via router links in the `MainLayout` ).

That is not possible with V8 components: V8 components may not be a navigation target annotated with `@Route` .

Also it's hard to say what is the view here: the navigation target `AnotherTarget` or its parent layout `MainLayout`.

In addition to that the `"root"` target definition :
```
@Route(value = "", layout = MainLayout.class)
public class NavigationTarget extends Div implements HasLegacyComponents {

    @Inject
    @RouteScopeOwner(MainLayout.class)
    private ViewScopedComponent component;

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        add(component);
    }
}

@RouteScoped
@RouteScopeOwner(MainLayout.class)
public class ViewScopedComponent extends VerticalLayout {

    public ViewScopedComponent() {
        Label label = new Label();
        addComponent(label);
        Button button = new Button("set label text",
                event -> label.setValue("foo"));

        addComponent(button);
    }
}
```
contain an injection point which has `RouteScopeOwner` qualifier and the `ViewScopedComponent` has scope `@RouteScoped`.
And this is the real example with V8 component which can be seen as `@ViewScoped` (again the button click allows to set the label value and see that it's preserved during navigation).

In this case view is not the navigation target `NavigationTarget`  but the `MainLayout`.

So this is an example how to use `@RouteScoped`  scope V8 component with a Flow parent layout as a view (`NavigationTarget` instance is not `@RouteScoped`  and its instance is not preserved during navigation and back).

Here is another example with V8 components hierarchy which uses that navigation target as a view:

```
mport com.vaadin.ui.Button;

@Route("no-layout")
public class NoLayoutTarget extends Div implements HasLegacyComponents {

    @Inject
    private Instance<LegacyLayout1> layout1;

    @Inject
    private Instance<LegacyLayout2> layout2;

    private boolean isFirstLayout;

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        add(layout1.get());
        isFirstLayout = true;

        Button button = new Button("change layout", event -> {
            removeAll();
            if (isFirstLayout) {
                add(layout2.get());
            } else {
                add(layout1.get());
            }
            isFirstLayout = !isFirstLayout;
        });
        add(button);
    }
}

import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class LegacyLayout1 extends VerticalLayout {

    @Inject
    @RouteScopeOwner(NoLayoutTarget.class)
    private Label label;

    @Override
    public void attach() {
        super.attach();

        label.setValue("foo");
        addComponents(new TextArea(), label);
    }

}

import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class LegacyLayout2 extends VerticalLayout {

    @Inject
    @RouteScopeOwner(NoLayoutTarget.class)
    private ScopedLabel label;

    @Override
    public void attach() {
        super.attach();

        addComponents(new Label("bar"), label);
    }
}

@RouteScopeOwner(NoLayoutTarget.class)
@RouteScoped
public class ScopedLabel extends Label {

}
```
`NoLayoutTarget` is the only Flow component here which is the navigation target.

All other components are V8 components whose hierarchy changes via button.
`LegacyLayout1` and `LegacyLayout2` instances are not preserved (they are injected via `Instance` ).
But the `ScopedLabel` has `@RouteScoped` with `NoLayoutTarget` as an owner and it's preserved when the content of the `NoLayoutTarget`  instance is replaced.
Here `NoLayoutTarget`  is a view.


So: it's possible to use `@RouteScoped` scope in MPR instead of `@ViewScoped` .
The only thing which needs to be done: determine the **view** which should be a Flow component: it may be a parent layout or a navigation target (`@Route`). The `@RouteScopeOwner(YourViewClass.class)` qualifier should be used in addition to the scope declaration and injection point.
