### ISSUE TITLE
Flow Spring 12.2 nightly build for Bower mode fails

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/spring#605]
https://bender.vaadin.com/viewLog.html?buildId=141258&tab=buildResultsDiv&buildTypeId=Flow_AddOns_FlowSpring122BowerMode

**Comment by mshabarov** [comment]
Spring 12.2 nightly builds have been failing time to time with the exception:

`Could not contact Spring Boot application: Failed to retrieve RMIServer stub: javax.naming.CommunicationException`

As a [workaround](https://serverfault.com/questions/308662/how-do-i-fix-a-failed-to-retrieve-rmiserver-stub-jmx-error) proposed, the JMX and RMI ports are explicitly set to the same value. Proposed to keep it under observation in 12.2 branch for nightly builds and see if the issue is gone.

**Comment by mshabarov** [comment]
The problem seems to be in interconnection between `spring-boot-maven-plugin` and started `spring-boot` application via JMX/RMI:

`Could not contact Spring Boot application: Failed to retrieve RMIServer stub: javax.naming.CommunicationException`

To eliminate that, I disabled fork mode in `spring-boot-maven-plugin` configuration and moved the parameter `vaadin.compatibilityMode=true` to all `application.properties`. But this time i get the following:

`java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.`

Setting `vaadin.productionMode=false` does help pass the `Clean install, no tests` step, but fails the next step `Run validation` and the following test are under failure now:

```
ComponentAddedViaInitListenerIT.componentAddedViaInitListenerIsLoaded[ANY_Chrome_] |  
-- | --
ComponentTestIT.componentsAreFoundAndLoaded[ANY_Chrome_] |  
ParentTemplateIT.customElementIsRegistered[ANY_Chrome_] |  
ParentTemplateIT.injectedComponentIsSpringManaged[ANY_Chrome_] |  
TemplatePushIT.callFunctionPushed[ANY_Chrome_] |  
TemplatePushIT.elementChangesPushed[ANY_Chrome_] |  
TemplatePushIT.execJsPushed[ANY_Chrome_] |  
UploadIT.uploadComponentIsInitialized[ANY_Chrome_]
```

So, the next step would be either to find another solution for initial JMX problem, or try another way to set `vaadin.compatibilityMode=true`.

**Comment by mshabarov** [comment]
Finally, the fork disable approach has been implemented. Compatibility mode is set in java code just before spring application start: true if bower profile is activated via system property, false - otherwise.
