### ISSUE TITLE
Vaadin Properties should be read from the environment using the Spring uniform name

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/spring#637]
According to this documentation:
`If you read properties from the environment in your application, you will now need to use the uniform name for the property.`

https://github.com/spring-projects/spring-boot/wiki/relaxed-binding-2.0#reading-properties-from-the-environment

This means that vaadin.productionMode is incorrect and should not be read by this add-on.
`env.getProperty("vaadin.productionMode")`

It should be read this way:
`env.getProperty("vaadin.production-mode")`

In practice Spring will bound the property by removing any special characters and converting to lowercase. For example, the following properties all result in the mapping 
vaadin.productionmode=true :
```
vaadin.production-mode=true
vaadin.productionMode=true
vaadin.productionMODE=true
```
The recommendation is that properties are stored in lowercase kabab format. i.e. vaadin.production-mode=true. 
So it won't introduce a breaking change and will reduce the chance or typo error for the user.

All the properties read from Vaadin flow should follow this rules.

This issue is linked to this one: https://github.com/vaadin/spring/issues/634 which asks vaadin property metadata.

**Comment by seletz** [comment]
Is this / will this be merged to vaadin 14?  This has bitten me -- and probably others -- and debugging this is very hard for ppl new to vaadin.

See https://vaadin.com/forum/thread/18400081/vaadin-14-spring-boot-vaadin-takes-over-all-web-requests-how-to-confi

**Comment by Numbernick** [comment]
I was led to this issue using spring boot and Intellij. Vaadin was responding to error requests instead of my spring configured error handler. So I found this stackoverflow article: [How to move the vaadin servlet to a different url](https://stackoverflow.com/questions/63396205/vaadin-14-how-to-move-the-vaadin-servlet-to-a-different-url). The problem is, the documentation is different than the autocompletion of Intellij for spring boot properties. This really is missleading.
![image](https://user-images.githubusercontent.com/9518580/99946819-4d874180-2d77-11eb-87cc-8b97130176b5.png)
Versions: Vaadin 17.0.9, Spring boot 2.3.0.RELEASE

**Comment by seletz** [comment]
Hi,

yes, we figured that one out.  IIRC there was a lengthy discussion in the vaadin forum about this issue.  It’s pretty annoying – the spring externalized configuration system is not used for vaadin properties as it seems, but
somehow IntelliJ figures out the property gives wrong advice.  This is in fact the first and only time inelliJ wronged me – that’s why I it took way too long to figure out … :/

--
Stefan Eletzhofer, nexiles GmbH
Mobil: +49 151 58 5 58 096


Von: Oliver Michalke <notifications@github.com>
Datum: Montag, 23. November 2020 um 10:35
An: vaadin/spring <spring@noreply.github.com>
Cc: Stefan Eletzhofer <stefan.eletzhofer@nexiles.com>, Comment <comment@noreply.github.com>
Betreff: Re: [vaadin/spring] Vaadin Properties should be read from the environment using the Spring uniform name (#637)

I was led to this issue using spring boot and Intellij. Vaadin was responding to error requests instead of my spring configured error handler. So I found this stackoverflow article: How to move the vaadin servlet to a different url<https://stackoverflow.com/questions/63396205/vaadin-14-how-to-move-the-vaadin-servlet-to-a-different-url>. The problem is, the documentation is different than the autocompletion of Intellij for spring boot properties. This really is missleading.
[image]<https://user-images.githubusercontent.com/9518580/99946819-4d874180-2d77-11eb-87cc-8b97130176b5.png>
Versions: Vaadin 17.0.9, Spring boot 2.3.0.RELEASE

**Comment by jcgueriaud1** [comment]
It's "fixed" in vaadin-spring 12.3.2. If you upgrade your application to the latest Vaadin 14 (14.4.2 has this fix, 14.3.8 not), you should be able to use vaadin.urlmapping, vaadin.urlMapping or vaadin.url-mapping.
I'm not sure if it's fixed in Vaadin 17 (but try to upgrade to the latest).

IntelliJ is giving the wrong advice (or no advice at all) because there is no metadata generated by Spring or manually added in this add-on.

I've opened an issue here: https://github.com/vaadin/spring/issues/689
Feel free to comment.

**Comment by Frettman** [comment]
> It's "fixed" in vaadin-spring 12.3.2. If you upgrade your application to the latest Vaadin 14 (14.4.2 has this fix, 14.3.8 not), you should be able to use vaadin.urlmapping, vaadin.urlMapping or vaadin.url-mapping.

For this property specifically, it's unfortunately not fixed in the version mentioned above. It appears one crucial location was missed where this property is used: `RootMappedCondition`.
This class still explicitly requests `vaadin.urlMapping`, so `vaadin.url-mapping` is not found.

**Comment by farhan00hm** [comment]
I used swagger (springdoc-openapi-ui) for my project. It was running well. But after add vaadin (22.0.2) to my project i am unable to access swagger URL (Could not navigate to 'swagger-ui/index.html') and show the available vaadin routes. when i add  vaadin.urlMapping=/ui/* then i am able to access swagger URL but my vaadin pages doesn't rendered.

**Comment by jcgueriaud1** [comment]
You should open a new ticket since your problem is different.
