### ISSUE TITLE
Vaadin handle Spring security's routes

### ISSUE THREAD

**Issue by gronono** [vaadin/spring#660]
Hello,

I'm trying to identify users using OAuth2 protocol.
I followed the tutorial https://vaadin.com/learn/tutorials/google-login.
And I manage to reproduce the problem with the example https://github.com/vaadin/vaadin-oauth-example.
It works correctly with Vaadin in version 14.2.3.
But when I update to version 17.0.2, Vaadin considers that the '/oauth2/authorization/google' route does not exist even though it is managed through Spring Security.

Steps to reproduce:
* clone project https://github.com/vaadin/vaadin-oauth-example
* change Vaadin's version in pom.xml file
* fix compilation problem in SecurityConfiguration by replacing ServletHelper with HandlerHelper

Regards

**Comment by haijian-vaadin** [comment]
Hi @gronono, thanks for reaching out. I think the problem is that in Vaadin 17, vaadin router handles all the Anchors (<a>) by default, you can let vaadin ignore that by `anchor.getElement().setAttribute("router-ignore", true);`

In the [LoginScreen of the example](https://github.com/vaadin/vaadin-oauth-example/blob/master/src/main/java/com/vaadin/example/oauth/ui/LoginScreen.java#L46) you are following, you can add such code to let Vaadin ignore the link for routing, i.e.
`gplusLoginButton.getElement().setAttribute("router-ignore", true);`
Then I think it should work.

**Comment by gronono** [comment]
Actually it works with "router-ignore" attribute.
Thanks @haijian-vaadin.
