### ISSUE TITLE
When deploying to a Tomcat server, SpringRouteNotFoundError is still active although being fixed

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/spring#661]
Related issue: https://github.com/vaadin/flow/issues/8948

I checked the war and webapps, and all of them contain **14.0.2**. When locally tested, it works, but when deployed to my webserver **it still shows the error of the related issue**.

```
Version: 14.0.2
Vaadin Version: 17.0.3
Java: Adopt Openjdk 14
```

**Comment by caalador** [comment]
Which web server does the deployment fail on?

**Comment by TheSilentHorizon** [comment]
@caaldor Tomcat 9.0.21

**Comment by caalador** [comment]
Exception happens when executing on the server as the exceptions are collected through the `ServletContextInitializer` and not by VaadinServletContextInitializer for Spring.

Workaround is to extend the Spring exception handler:
`public class CustomNotFoundHandler extends SpringRouteNotFoundError {`
