### ISSUE TITLE
VaadinServletContextInitializer is not serializable

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/spring#681]
Class `VaadinServletContextInitializer` is not serializable, but all of its classes are non-static hence contain reference to it. This effectively makes (correct me if I'm wrong) the following classes non-serializable:
- `AnnotationValidatorServletContextListener`
- `DevModeServletContextListener`
- `ErrorParameterServletContextListener`
- `RouteServletContextListener`
- `VaadinAppShellContextListener`
- `WebComponentServletContextListener`

**Comment by pleku** [comment]
ServletContextInitializer is only run when the application is started and it is not needed after that and thus should not be needed to be serialized. I can't figure out any reason why anyone would keep a reference to any of the mentioned classes other than as a mistake or due to doing something that is not supported. Closing as a wontfix

**Comment by fluorumlabs** [comment]
Could that cause issues when servlet is migrated to different JVM?
