### ISSUE TITLE
Spike: investigate how routescope could work with Vaadin Spring

### ISSUE THREAD

**Issue by pleku** [vaadin/spring#785]
The idea has been that the `@RouteScope` would work the same way for spring as it does for CDI https://vaadin.com/docs/v14/flow/integrations/cdi/tutorial-cdi-contexts/#routescoped-and-normalroutescoped-contexts. But there are open questions to whether it makes sense or not to require two annotations instead of just one for the scope, since it is mandatory in CDI currently. This issue is about investigating whether or not we could use one annotation instead of two, meaning that the _owner_ of the route scope is given as a parameter in the annotation. If it is not possible (like with CDI), then it would be good if we can spot the errors by the users and help them resolve those (forgetting the owner).

**Comment by denis-anisimov** [comment]
Every scope is identified via a unique name (a string).
So it's not possible to have parameterized scope because parameter value changes the scope and it means parameter should 
influence on the scope identifier.
The annotations `SomeScope` is just a convenience for `@Scope("some-scope-unique-name")`. And it shows that parameter may not be used since the scope unique id should be based on parameter name.

Theoretically we may register a scope on the fly : generate unique scope id , register a scope .
But then the question which has no answer: how to use such generated scope. The unique id is not known which means you can't use `@Scope("some-generated-unique-id")` because noone knows the `"some-generated-unique-id"`.

Introducing a "pseudo-scope" (some annotation with a parameter which is not a Spring scope) will require quite deep Spring knowledge and using Spring deep internals: we have to scan for the annotation (this is possible) and then the object factory should be aware of the custom annotation (since it's not a scope): this is re-invention Spring scope mechanism almost from scratch (or better to say reusing the basic Spring internal logic related to Scope which may be is not even possible).

**So as a result : I suggest avoid an attempt to get rid of the second annotation which allows to specify the owner.**

Using a qualifier as such annotation looks as the most appropriate way (the same as in CDI).

The problem is still valid: it's really error-prone to have `@RouteScope` without any qualifier (which specifies the owner).

So either we should scan for all `@RouteScope`  annotations and check whether any annotation usage also has a qualifier (with explicit owner). If there is no a qualifier then throws (same as AnnotationValidator at the startup).

Or **if it's possible** check the presence of the qualifier when a scope is asked to return a bean somehow.
I'm not sure how feasible to add this check since scope itself is not aware of the qualifier presence. It's the framework internals which selects the eligible bean based on specified qualifiers: that's why the qualifier is not really a proper solution to specify the owner.
CDI has a validator which checks the bean info based on `javax.enterprise.inject.spi.Bean`. This info is able to access the qualifiers.
I can't find similar functionality in Spring but if it's possible then we should just make similar validator and throw if a bean with `@RouteScope`  has no qualifier which specifies the owner.

The suggestion is : avoid implicit owner (like it's done in CDI where the absence of qualifier with owner means the parent as an owner). We should disable implicit owner in CDI as well: the qualifier with owner has to be required.
