### ISSUE TITLE
Using url mapping breaks static resources

### ISSUE THREAD

**Issue by TatuLund** [vaadin/spring#863]
Steps to reproduce

Go to start.vaadin.com and generate Java only application with some views

Modify the application as follows

Add the following url mapping to application.properties

`vaadin.urlMapping=/ui/*`

Add frontend servlet bean defintion according to our tutorial to Application.java

https://raw.githubusercontent.com/vaadin/flow-and-components-documentation/master/tutorial-servlet-spring-boot/src/main/java/org/vaadin/tutorial/spring/Application.java

Start the application using spring-boot:run

Open the application using http://localhost:8080/ui/ as url

The application works otherwise properly, but the starter logo is broken

![image](https://user-images.githubusercontent.com/14309836/127122186-c2a1040b-beef-4af9-97fc-706e8aa869a4.png)

Inspecting MainView.java shows that image is used correctly

`logoLayout.add(new Image("images/logo.png", "Starter logo"));`

**Comment by denis-anisimov** [comment]
You are using **Spring**.
All the problem comes from this.

The image location is http://localhost:8080/images/logo.png.
Because `logo.png` is located in the `META-INF/resources/images/logo.png`. This folder is served by _Spring_ and not by Vaadin because Spring apparently is able to handle the URL by the default dispatcher but it doesn't place the resource path `images/logo.png`  into the Servlet context.
Vaadin handles the resource which are available via the Servlet context.

So either : 
- inspect Spring documentation
- Use `new Image("/images/logo.png", "Starter logo")` instead of `new Image("images/logo.png", "Starter logo")``
- Use servlet context instead of URL mapping .

This is how Spring works and yes, it's always unexpected.
Not a Vaadin issue.
