### ISSUE TITLE
Does not work with Spring Boot 2.6

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#941]
Seems like Spring Boot 2.6 removed `ResourceProperties` which is used in some hacky code in https://github.com/vaadin/spring/blob/dee6efa77a5cb4455ebcc244b4a25778b2eeefa4/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L136

**Comment by lmorocz** [comment]
Hi! Sadly it's also a runtime problem with Spring Boot 2.6.x and every Vaadin version ATM. Because of the removed class, the ` isSpringBootConfigured()` returns `false`, and SpringVaadinServletService doesn't serve Spring static assets anymore. :( 

See: https://github.com/vaadin/spring/blob/25daa752842b130d4b1e82481cc27acd229c70d7/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java

Previous Spring Boot versions are OK.
